package store

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

const postgresMigrationLock int64 = 0x414E584442

type postgresMigration struct {
	version int
	name    string
	sql     string
}

func postgresBaseSchema() string {
	schema := sqliteCoreSchema + "\n" + observationSchema
	schema = strings.ReplaceAll(schema, " BLOB ", " BYTEA ")
	schema = strings.ReplaceAll(schema, " INTEGER", " BIGINT")
	schema = strings.ReplaceAll(schema, " REAL", " DOUBLE PRECISION")
	schema = strings.ReplaceAll(schema, "\tcontroller_id TEXT,\n\tcontroller_id TEXT,\n", "\tcontroller_id TEXT,\n")
	lines := strings.Split(schema, "\n")
	filtered := lines[:0]
	for _, line := range lines {
		if strings.Contains(line, "json_extract(") {
			continue
		}
		filtered = append(filtered, line)
	}
	return strings.Join(filtered, "\n")
}

func postgresMigrations() []postgresMigration {
	return []postgresMigration{
		{
			version: 1,
			name:    "postgres_base_schema",
			sql: postgresBaseSchema() + `
ALTER TABLE providers ADD COLUMN IF NOT EXISTS in_failover_queue BIGINT DEFAULT 0;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS sort_index BIGINT DEFAULT 0;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS conversation_id TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS trace_id TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS turn_id TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS request_id TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS runtime_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS request_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS trace_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS parent_span_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS attempt BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS parent_attempt_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS started_at TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS ttft_ms BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS duration_ms BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS stream_complete BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS finish_reason TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS input_tokens BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS output_tokens BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS cache_read_tokens BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS cache_write_tokens BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS request_bytes BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS response_bytes BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS cost_usd DOUBLE PRECISION DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_request
	ON usage_records(source,request_id,host) WHERE request_id IS NOT NULL AND request_id<>'';
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversations_active
	ON conversations(scope, conversation_key) WHERE ended_at IS NULL OR ended_at='';
`,
		},
		{
			version: 2,
			name:    "observation_batching_and_indexes",
			sql: `
ALTER TABLE observation_events
	ADD COLUMN IF NOT EXISTS ingestion_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_observation_events_ingestion_seq
	ON observation_events(ingestion_seq);
CREATE INDEX IF NOT EXISTS idx_observation_events_timestamp_brin
	ON observation_events USING BRIN(timestamp);
CREATE INDEX IF NOT EXISTS idx_observation_spans_session_started
	ON observation_spans(session_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_observation_spans_tool_call
	ON observation_spans(((tool_json::jsonb)->>'call_id')) WHERE tool_json IS NOT NULL AND tool_json<>'null';
CREATE INDEX IF NOT EXISTS idx_observation_spans_model_request
	ON observation_spans(((model_json::jsonb)->>'request_id')) WHERE model_json IS NOT NULL AND model_json<>'null';
CREATE TABLE IF NOT EXISTS observation_dirty_traces (
	trace_id TEXT PRIMARY KEY,
	touched_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_observation_dirty_traces_touched
	ON observation_dirty_traces(touched_at);
ALTER TABLE observation_events SET (
	autovacuum_vacuum_scale_factor = 0.02,
	autovacuum_analyze_scale_factor = 0.01
);
ALTER TABLE observation_spans SET (
	autovacuum_vacuum_scale_factor = 0.02,
	autovacuum_analyze_scale_factor = 0.01
);
`,
		},
		{
			version: 3,
			name:    "observation_native_types",
			sql: `
DROP INDEX IF EXISTS idx_observation_spans_tool_call;
DROP INDEX IF EXISTS idx_observation_spans_model_request;
ALTER TABLE observation_traces
	ALTER COLUMN provenance TYPE JSONB USING COALESCE(NULLIF(provenance,''),'null')::jsonb,
	ALTER COLUMN error_json TYPE JSONB USING COALESCE(NULLIF(error_json,''),'null')::jsonb,
	ALTER COLUMN model_json TYPE JSONB USING COALESCE(NULLIF(model_json,''),'null')::jsonb,
	ALTER COLUMN attributes TYPE JSONB USING COALESCE(NULLIF(attributes,''),'null')::jsonb;
ALTER TABLE observation_spans
	ALTER COLUMN provenance TYPE JSONB USING COALESCE(NULLIF(provenance,''),'null')::jsonb,
	ALTER COLUMN error_json TYPE JSONB USING COALESCE(NULLIF(error_json,''),'null')::jsonb,
	ALTER COLUMN model_json TYPE JSONB USING COALESCE(NULLIF(model_json,''),'null')::jsonb,
	ALTER COLUMN tool_json TYPE JSONB USING COALESCE(NULLIF(tool_json,''),'null')::jsonb,
	ALTER COLUMN attributes TYPE JSONB USING COALESCE(NULLIF(attributes,''),'null')::jsonb;
ALTER TABLE observation_events
	ALTER COLUMN envelope_json TYPE JSONB USING envelope_json::jsonb;
ALTER TABLE observation_export_outbox ALTER COLUMN include_content DROP DEFAULT;
ALTER TABLE observation_export_outbox
	ALTER COLUMN envelope_json TYPE JSONB USING envelope_json::jsonb,
	ALTER COLUMN include_content TYPE BOOLEAN USING include_content<>0;
ALTER TABLE observation_export_outbox ALTER COLUMN include_content SET DEFAULT FALSE;
ALTER TABLE observation_payloads ALTER COLUMN redacted DROP DEFAULT;
ALTER TABLE observation_payloads
	ALTER COLUMN redacted TYPE BOOLEAN USING redacted<>0;
ALTER TABLE observation_payloads ALTER COLUMN redacted SET DEFAULT FALSE;
ALTER TABLE observation_insights ALTER COLUMN only_suggestion DROP DEFAULT;
ALTER TABLE observation_insights
	ALTER COLUMN related_trace_ids TYPE JSONB USING COALESCE(NULLIF(related_trace_ids,''),'[]')::jsonb,
	ALTER COLUMN only_suggestion TYPE BOOLEAN USING only_suggestion<>0;
ALTER TABLE observation_insights ALTER COLUMN only_suggestion SET DEFAULT TRUE;
ALTER TABLE observation_integration_ownership
	ALTER COLUMN metadata TYPE JSONB USING COALESCE(NULLIF(metadata,''),'null')::jsonb;
ALTER TABLE observation_resource_leases
	ALTER COLUMN metadata TYPE JSONB USING COALESCE(NULLIF(metadata,''),'null')::jsonb;
CREATE INDEX IF NOT EXISTS idx_observation_spans_tool_call
	ON observation_spans((tool_json->>'call_id')) WHERE tool_json IS NOT NULL AND tool_json<>'null'::jsonb;
CREATE INDEX IF NOT EXISTS idx_observation_spans_model_request
	ON observation_spans((model_json->>'request_id')) WHERE model_json IS NOT NULL AND model_json<>'null'::jsonb;
`,
		},
		{
			version: 4,
			name:    "usage_timestamp_index",
			sql: `
CREATE INDEX IF NOT EXISTS idx_usage_timestamp ON usage_records(timestamp);
`,
		},
	}
}

func (s *Store) migratePostgres(ctx context.Context) error {
	conn, err := s.db.Conn(ctx)
	if err != nil {
		return fmt.Errorf("acquire postgres migration connection: %w", err)
	}
	defer conn.Close()
	if _, err := conn.ExecContext(ctx, `SELECT pg_advisory_lock($1)`, postgresMigrationLock); err != nil {
		return fmt.Errorf("lock postgres migrations: %w", err)
	}
	defer func() {
		_, _ = conn.ExecContext(context.WithoutCancel(ctx), `SELECT pg_advisory_unlock($1)`, postgresMigrationLock)
	}()
	if _, err := conn.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
		version INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
	)`); err != nil {
		return fmt.Errorf("create schema_migrations: %w", err)
	}
	for _, migration := range postgresMigrations() {
		var exists bool
		err := conn.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE version=$1)`, migration.version).Scan(&exists)
		if err != nil {
			return fmt.Errorf("read migration %d: %w", migration.version, err)
		}
		if exists {
			continue
		}
		tx, err := conn.BeginTx(ctx, &sql.TxOptions{})
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, migration.sql); err != nil {
			_ = tx.Rollback()
			return fmt.Errorf("apply postgres migration %d (%s): %w", migration.version, migration.name, err)
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO schema_migrations(version,name) VALUES($1,$2)`, migration.version, migration.name); err != nil {
			_ = tx.Rollback()
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
	}
	if _, err := conn.ExecContext(ctx, `UPDATE conversations
		SET conversation_key=CASE
			WHEN chat_id LIKE 'chat:%' OR chat_id LIKE 'thread:%' OR chat_id LIKE 'root:%' THEN chat_id
			ELSE 'chat:' || chat_id
		END
		WHERE conversation_key IS NULL OR conversation_key=''`); err != nil {
		return err
	}
	return s.migrateAgentBindings()
}
