package store

import (
	"context"
	"database/sql"
	_ "embed"
	"fmt"
)

const postgresMigrationLock int64 = 0x414E584442

type postgresMigration struct {
	version int
	name    string
	sql     string
}

//go:embed postgres_schema.sql
var postgresBaseSchemaSQL string

func postgresBaseSchema() string { return postgresBaseSchemaSQL }

func postgresMigrations() []postgresMigration {
	return []postgresMigration{
		{
			version: 1,
			name:    "postgres_base_schema",
			sql: postgresBaseSchema() + `
ALTER TABLE providers ADD COLUMN IF NOT EXISTS in_failover_queue BIGINT DEFAULT 0;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS sort_index BIGINT DEFAULT 0;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS conversation_id TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS trace_id TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS turn_id TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS request_id TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS runtime_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS request_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS trace_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS parent_span_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS attempt BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS parent_attempt_id TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS started_at TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS ttft_ms BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS duration_ms BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS stream_complete BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS finish_reason TEXT;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS input_tokens BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS output_tokens BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS cache_read_tokens BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS cache_write_tokens BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS request_bytes BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS response_bytes BIGINT DEFAULT 0;
ALTER TABLE proxy_traces ADD COLUMN IF NOT EXISTS cost_usd DOUBLE PRECISION DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_request
	ON usage_records(source,request_id,host) WHERE request_id IS NOT NULL AND request_id<>'';
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversations_active
	ON conversations(scope, conversation_key) WHERE ended_at IS NULL OR ended_at='';
`,
		},
		{
			version: 2,
			name:    "observation_batching_and_indexes",
			sql: `
ALTER TABLE observation_events
	ADD COLUMN IF NOT EXISTS ingestion_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_observation_events_ingestion_seq
	ON observation_events(ingestion_seq);
CREATE INDEX IF NOT EXISTS idx_observation_events_timestamp_brin
	ON observation_events USING BRIN(timestamp);
CREATE INDEX IF NOT EXISTS idx_observation_spans_session_started
	ON observation_spans(session_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_observation_spans_tool_call
	ON observation_spans(((tool_json::jsonb)->>'call_id')) WHERE tool_json IS NOT NULL AND tool_json<>'null';
CREATE INDEX IF NOT EXISTS idx_observation_spans_model_request
	ON observation_spans(((model_json::jsonb)->>'request_id')) WHERE model_json IS NOT NULL AND model_json<>'null';
CREATE TABLE IF NOT EXISTS observation_dirty_traces (
	trace_id TEXT PRIMARY KEY,
	touched_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_observation_dirty_traces_touched
	ON observation_dirty_traces(touched_at);
ALTER TABLE observation_events SET (
	autovacuum_vacuum_scale_factor = 0.02,
	autovacuum_analyze_scale_factor = 0.01
);
ALTER TABLE observation_spans SET (
	autovacuum_vacuum_scale_factor = 0.02,
	autovacuum_analyze_scale_factor = 0.01
);
`,
		},
		{
			version: 3,
			name:    "observation_native_types",
			sql: `
DROP INDEX IF EXISTS idx_observation_spans_tool_call;
DROP INDEX IF EXISTS idx_observation_spans_model_request;
ALTER TABLE observation_traces
	ALTER COLUMN provenance TYPE JSONB USING COALESCE(NULLIF(provenance,''),'null')::jsonb,
	ALTER COLUMN error_json TYPE JSONB USING COALESCE(NULLIF(error_json,''),'null')::jsonb,
	ALTER COLUMN model_json TYPE JSONB USING COALESCE(NULLIF(model_json,''),'null')::jsonb,
	ALTER COLUMN attributes TYPE JSONB USING COALESCE(NULLIF(attributes,''),'null')::jsonb;
ALTER TABLE observation_spans
	ALTER COLUMN provenance TYPE JSONB USING COALESCE(NULLIF(provenance,''),'null')::jsonb,
	ALTER COLUMN error_json TYPE JSONB USING COALESCE(NULLIF(error_json,''),'null')::jsonb,
	ALTER COLUMN model_json TYPE JSONB USING COALESCE(NULLIF(model_json,''),'null')::jsonb,
	ALTER COLUMN tool_json TYPE JSONB USING COALESCE(NULLIF(tool_json,''),'null')::jsonb,
	ALTER COLUMN attributes TYPE JSONB USING COALESCE(NULLIF(attributes,''),'null')::jsonb;
ALTER TABLE observation_events
	ALTER COLUMN envelope_json TYPE JSONB USING envelope_json::jsonb;
ALTER TABLE observation_export_outbox ALTER COLUMN include_content DROP DEFAULT;
ALTER TABLE observation_export_outbox
	ALTER COLUMN envelope_json TYPE JSONB USING envelope_json::jsonb,
	ALTER COLUMN include_content TYPE BOOLEAN USING include_content<>0;
ALTER TABLE observation_export_outbox ALTER COLUMN include_content SET DEFAULT FALSE;
ALTER TABLE observation_payloads ALTER COLUMN redacted DROP DEFAULT;
ALTER TABLE observation_payloads
	ALTER COLUMN redacted TYPE BOOLEAN USING redacted<>0;
ALTER TABLE observation_payloads ALTER COLUMN redacted SET DEFAULT FALSE;
ALTER TABLE observation_insights ALTER COLUMN only_suggestion DROP DEFAULT;
ALTER TABLE observation_insights
	ALTER COLUMN related_trace_ids TYPE JSONB USING COALESCE(NULLIF(related_trace_ids,''),'[]')::jsonb,
	ALTER COLUMN only_suggestion TYPE BOOLEAN USING only_suggestion<>0;
ALTER TABLE observation_insights ALTER COLUMN only_suggestion SET DEFAULT TRUE;
ALTER TABLE observation_integration_ownership
	ALTER COLUMN metadata TYPE JSONB USING COALESCE(NULLIF(metadata,''),'null')::jsonb;
ALTER TABLE observation_resource_leases
	ALTER COLUMN metadata TYPE JSONB USING COALESCE(NULLIF(metadata,''),'null')::jsonb;
CREATE INDEX IF NOT EXISTS idx_observation_spans_tool_call
	ON observation_spans((tool_json->>'call_id')) WHERE tool_json IS NOT NULL AND tool_json<>'null'::jsonb;
CREATE INDEX IF NOT EXISTS idx_observation_spans_model_request
	ON observation_spans((model_json->>'request_id')) WHERE model_json IS NOT NULL AND model_json<>'null'::jsonb;
`,
		},
		{
			version: 4,
			name:    "usage_timestamp_index",
			sql: `
CREATE INDEX IF NOT EXISTS idx_usage_timestamp ON usage_records(timestamp);
`,
		},
		{
			version: 5,
			name:    "agent_approval_mode",
			sql: `
ALTER TABLE agent_instances ADD COLUMN IF NOT EXISTS default_approval_mode TEXT;
`,
		},
		{
			version: 6,
			name:    "agent_workspace_policy",
			sql: `
ALTER TABLE agent_instances ADD COLUMN IF NOT EXISTS workspace_mode TEXT;
ALTER TABLE agent_instances ADD COLUMN IF NOT EXISTS worktree_base_ref TEXT;
ALTER TABLE agent_instances ADD COLUMN IF NOT EXISTS session_backend TEXT;
`,
		},
		{
			version: 7,
			name:    "channel_task_delivery_state",
			sql: `
ALTER TABLE channel_tasks ADD COLUMN IF NOT EXISTS delivery_key TEXT;
ALTER TABLE channel_tasks ADD COLUMN IF NOT EXISTS delivery_status TEXT;
ALTER TABLE channel_tasks ADD COLUMN IF NOT EXISTS delivery_attempts BIGINT DEFAULT 0;
ALTER TABLE channel_tasks ADD COLUMN IF NOT EXISTS delivery_error TEXT;
ALTER TABLE channel_tasks ADD COLUMN IF NOT EXISTS delivered_at TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_channel_tasks_delivery_key
	ON channel_tasks(delivery_key) WHERE delivery_key IS NOT NULL AND delivery_key <> '';
`,
		},
		{
			version: 8,
			name:    "channel_feedback",
			sql: `
ALTER TABLE channel_tasks ADD COLUMN IF NOT EXISTS feedback_nonce TEXT;
CREATE TABLE IF NOT EXISTS channel_feedback (
	id TEXT PRIMARY KEY,
	task_id TEXT NOT NULL,
	channel_id TEXT NOT NULL,
	conversation_id TEXT,
	user_id TEXT NOT NULL,
	semantic TEXT NOT NULL,
	reason TEXT,
	comment TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	UNIQUE(task_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_channel_feedback_channel_updated
	ON channel_feedback(channel_id, updated_at);
`,
		},
		{
			version: 9,
			name:    "orchestrations",
			sql: `
CREATE TABLE IF NOT EXISTS orchestrations (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	status TEXT NOT NULL,
	max_concurrency BIGINT NOT NULL,
	error TEXT,
	created_at TEXT NOT NULL,
	started_at TEXT,
	finished_at TEXT,
	updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS orchestration_tasks (
	orchestration_id TEXT NOT NULL,
	id TEXT NOT NULL,
	agent_id TEXT,
	project TEXT,
	input TEXT NOT NULL,
	depends_on TEXT,
	status TEXT NOT NULL,
	output TEXT,
	error TEXT,
	invocation_id TEXT,
	conversation_id TEXT,
	created_at TEXT NOT NULL,
	started_at TEXT,
	finished_at TEXT,
	updated_at TEXT NOT NULL,
	PRIMARY KEY(orchestration_id,id)
);
CREATE INDEX IF NOT EXISTS idx_orchestrations_status_updated
	ON orchestrations(status,updated_at);
CREATE INDEX IF NOT EXISTS idx_orchestration_tasks_status
	ON orchestration_tasks(orchestration_id,status);
`,
		},
		{
			version: 10,
			name:    "agent_desktop_thread",
			sql: `
ALTER TABLE agent_instances ADD COLUMN IF NOT EXISTS desktop_thread_id TEXT;
`,
		},
		{
			version: 11,
			name:    "tenancy",
			sql: `
CREATE TABLE IF NOT EXISTS tenants (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	kind TEXT,
	status TEXT NOT NULL,
	note TEXT,
	created_at TEXT,
	updated_at TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenants_name ON tenants(name);
CREATE TABLE IF NOT EXISTS tenant_tokens (
	id TEXT PRIMARY KEY,
	tenant_id TEXT NOT NULL,
	name TEXT,
	token_hash TEXT NOT NULL,
	prefix TEXT,
	created_at TEXT,
	last_used_at TEXT,
	expires_at TEXT,
	revoked_at TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_tokens_hash ON tenant_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_tenant_tokens_tenant ON tenant_tokens(tenant_id);
CREATE TABLE IF NOT EXISTS tenant_enrollments (
	id TEXT PRIMARY KEY,
	code_hash TEXT NOT NULL,
	name_hint TEXT,
	kind_hint TEXT,
	tenant_id TEXT,
	created_at TEXT,
	expires_at TEXT,
	consumed_at TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_enrollments_code ON tenant_enrollments(code_hash);
CREATE TABLE IF NOT EXISTS resource_grants (
	tenant_id TEXT NOT NULL,
	resource_type TEXT NOT NULL,
	resource_id TEXT NOT NULL,
	level TEXT NOT NULL,
	created_at TEXT,
	updated_at TEXT,
	PRIMARY KEY (tenant_id, resource_type, resource_id)
);
CREATE INDEX IF NOT EXISTS idx_resource_grants_lookup ON resource_grants(tenant_id, resource_type);
ALTER TABLE agent_instances ADD COLUMN IF NOT EXISTS owner_tenant_id TEXT;
ALTER TABLE agent_instances ADD COLUMN IF NOT EXISTS visibility TEXT;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS owner_tenant_id TEXT;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS visibility TEXT;
ALTER TABLE triggers ADD COLUMN IF NOT EXISTS owner_tenant_id TEXT;
ALTER TABLE orchestrations ADD COLUMN IF NOT EXISTS owner_tenant_id TEXT;
CREATE INDEX IF NOT EXISTS idx_agent_instances_owner ON agent_instances(owner_tenant_id);
CREATE INDEX IF NOT EXISTS idx_channels_owner ON channels(owner_tenant_id);
CREATE INDEX IF NOT EXISTS idx_triggers_owner ON triggers(owner_tenant_id);
CREATE INDEX IF NOT EXISTS idx_orchestrations_owner ON orchestrations(owner_tenant_id);
`,
		},
		{
			version: 12,
			name:    "remove_tenant_enrollment_codes",
			sql: `
DROP TABLE IF EXISTS tenant_enrollments;
`,
		},
		{
			version: 13,
			name:    "usage_quality_and_provenance",
			sql: `
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS provenance TEXT;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS provenance_rank BIGINT DEFAULT 0;
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS token_quality TEXT DEFAULT 'exact';
ALTER TABLE usage_records ADD COLUMN IF NOT EXISTS cost_kind TEXT DEFAULT 'calculated';
`,
		},
		{
			version: 14,
			name:    "persistent_skill_states",
			sql: `
CREATE TABLE IF NOT EXISTS skill_states (
	name TEXT PRIMARY KEY,
	enabled BIGINT NOT NULL DEFAULT 1,
	updated_at TEXT NOT NULL
);
`,
		},
	}
}

func (s *Store) migratePostgres(ctx context.Context) error {
	conn, err := s.db.Conn(ctx)
	if err != nil {
		return fmt.Errorf("acquire postgres migration connection: %w", err)
	}
	defer conn.Close()
	if _, err := conn.ExecContext(ctx, `SELECT pg_advisory_lock($1)`, postgresMigrationLock); err != nil {
		return fmt.Errorf("lock postgres migrations: %w", err)
	}
	defer func() {
		_, _ = conn.ExecContext(context.WithoutCancel(ctx), `SELECT pg_advisory_unlock($1)`, postgresMigrationLock)
	}()
	if _, err := conn.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
		version INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
	)`); err != nil {
		return fmt.Errorf("create schema_migrations: %w", err)
	}
	for _, migration := range postgresMigrations() {
		var exists bool
		err := conn.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE version=$1)`, migration.version).Scan(&exists)
		if err != nil {
			return fmt.Errorf("read migration %d: %w", migration.version, err)
		}
		if exists {
			continue
		}
		tx, err := conn.BeginTx(ctx, &sql.TxOptions{})
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, migration.sql); err != nil {
			_ = tx.Rollback()
			return fmt.Errorf("apply postgres migration %d (%s): %w", migration.version, migration.name, err)
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO schema_migrations(version,name) VALUES($1,$2)`, migration.version, migration.name); err != nil {
			_ = tx.Rollback()
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
	}
	if _, err := conn.ExecContext(ctx, `UPDATE conversations
		SET conversation_key=CASE
			WHEN chat_id LIKE 'chat:%' OR chat_id LIKE 'thread:%' OR chat_id LIKE 'root:%' THEN chat_id
			ELSE 'chat:' || chat_id
		END
		WHERE conversation_key IS NULL OR conversation_key=''`); err != nil {
		return err
	}
	return s.migrateAgentBindings()
}
